### ISSUE TITLE
No color highlighting on opened loot

### ISSUE THREAD

**Issue by Kazbin** [sitnaltax/loot-box-clicker#49]
Whenever chests are opened items with higher power than equipped ones are not shown in color green, as the class is missing...

**Comment by Exportforce** [comment]
I really suggest to add a version number and change log to the game itself too. So you can check the live changes and don't have to guess if the changes to the source are already live. Did also update like a madman to see the change with coloring.

**Comment by sitnaltax** [comment]
The fixed version is live! I'll open a separate issue for putting the changelog in the game.
