### ISSUE TITLE
Should upgrading items trigger auto donation?

### ISSUE THREAD

**Issue by Octoshape** [sitnaltax/loot-box-clicker#74]
The way it's currently implemented, when an item is upgraded from the inventory, the previously equipped item gets added back to the inventory, and with it, the auto donation gets triggered.

Is this intentional? I was just confused as sometimes I would get back the old piece (since it's only a chance to auto donate) and I would see "how big" the upgrade is and sometimes it gets donated instantly.

**Comment by sitnaltax** [comment]
It's not intentional, but there's no particular reason not to--there's no reason to hold onto an old piece of equipment.
